package com.user.wechat.db.domains;

// Generated 2015-10-10 22:18:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ArticleCatalog generated by hbm2java
 */
public class ArticleCatalog implements java.io.Serializable {

	private static final long serialVersionUID = -5269898641269271166L;
	
	private Integer id;
	
	private String title;
	
	private String description;
	
	private String bigPicUrl;
	
	private String smallPicUrl;
	
	private String url;
	
	private Date publishTime;

	public ArticleCatalog() {
	}

	public ArticleCatalog(String title, Date publishTime) {
		this.title = title;
		this.publishTime = publishTime;
	}

	public ArticleCatalog(String title, String description, String bigPicUrl, String smallPicUrl, String url, Date publishTime) {
		this.title = title;
		this.description = description;
		this.bigPicUrl = bigPicUrl;
		this.smallPicUrl = smallPicUrl;
		this.url = url;
		this.publishTime = publishTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getBigPicUrl() {
		return this.bigPicUrl;
	}

	public void setBigPicUrl(String bigPicUrl) {
		this.bigPicUrl = bigPicUrl;
	}

	public String getSmallPicUrl() {
		return this.smallPicUrl;
	}

	public void setSmallPicUrl(String smallPicUrl) {
		this.smallPicUrl = smallPicUrl;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

}
