package com.user.wechat.db.domains;

// Generated 2015-9-19 11:11:38 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DeveloperInfo generated by hbm2java
 */
public class DeveloperInfo implements java.io.Serializable {

	private static final long serialVersionUID = -2240082887640870426L;
	
	private Integer id;
	
	private int userInfoId;
	
	private String developerId;
	
	private Date registTime;

	public DeveloperInfo() {
	}

	public DeveloperInfo(int userInfoId, String developerId, Date registTime) {
		this.userInfoId = userInfoId;
		this.developerId = developerId;
		this.registTime = registTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUserInfoId() {
		return this.userInfoId;
	}

	public void setUserInfoId(int userInfoId) {
		this.userInfoId = userInfoId;
	}

	public String getDeveloperId() {
		return this.developerId;
	}

	public void setDeveloperId(String developerId) {
		this.developerId = developerId;
	}

	public Date getRegistTime() {
		return this.registTime;
	}

	public void setRegistTime(Date registTime) {
		this.registTime = registTime;
	}

}
