package com.user.wechat.db.domains;

// Generated 2015-10-24 19:20:22 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * UserTrace generated by hbm2java
 */
public class UserTrace implements java.io.Serializable {

	private static final long serialVersionUID = 1883459939090665467L;

	private Integer id;

	private String openId;

	private BigDecimal latitude;

	private BigDecimal longitude;

	private BigDecimal prcsn;

	private Integer scale;

	private String label;

	private Date recordTime;

	public UserTrace() {

	}

	public UserTrace(String openId, BigDecimal latitude, BigDecimal longitude, Date recordTime) {
		this.openId = openId;
		this.latitude = latitude;
		this.longitude = longitude;
		this.recordTime = recordTime;
	}

	public UserTrace(String openId, BigDecimal latitude, BigDecimal longitude, BigDecimal prcsn, Integer scale, String label, Date recordTime) {
		this.openId = openId;
		this.latitude = latitude;
		this.longitude = longitude;
		this.prcsn = prcsn;
		this.scale = scale;
		this.label = label;
		this.recordTime = recordTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOpenId() {
		return this.openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	public BigDecimal getPrcsn() {
		return this.prcsn;
	}

	public void setPrcsn(BigDecimal prcsn) {
		this.prcsn = prcsn;
	}

	public Integer getScale() {
		return this.scale;
	}

	public void setScale(Integer scale) {
		this.scale = scale;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Date getRecordTime() {
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime) {
		this.recordTime = recordTime;
	}

}
